displayName=OneMan Sync
author=Catleris
description=Local Slayer preparation, locations and Prayer resources with optional account progression sync to oneman.lt
tags=progress,quests,ironman,sync,achievements,collection,log,boss,kc,pets,loot,clue,stash,slayer,storage,poh
version=
plugins=lt.oneman.sync.OneManSyncPlugin
build=standard
